#!/bin/bash

#clear

printf ""
cat /etc/elsojosmo
printf ""

echo "====STATUS=="
git status
echo "============"
echo

git diff >> $HOME/mytempo_changelog

read -p "Is this alright? [Y/n] " ALR

if [ ${ALR:-y} = "n" ] ; then
	echo "Aborting... be safe."
	exit
fi
echo

printf ""
read -p "Are you feeling dangerous? [y/N] " ISINSANE
printf ""

if [ "${ISINSANE:-y}" = "n" ] ; then
	git pull
	git submodule update --init --remote --recursive
fi

FUCKO=$(fucko)

git add -A

echo "COMMIT MESSAGE: $FUCKO"

git commit -m "$FUCKO" --quiet

if [ "${ISINSANE:-n}" = "y" ] ; then
	git push -f
else
	git push
fi

