#!/bin/sh

error() {
    printf "\033[31;1m$@\033[0m\n"

    exit 1
}

healthy_breakup() {
    printf "\033[32;1m$@\033[0m\n"

    exit 0
}

UPDATING=no

[ "$1" = "update" ] && UPDATING=yes

# if file doesnt exist, or we are updating, copy in files to env files

(test -e shared.env && [ "$UPDATING" = "no" ]) \
    || cp shared.env.in shared.env

(test -e Offline/AA2/aa2.env && [ "$UPDATING" = "no" ]) \
    || cp Offline/AA2/aa2.env.in Offline/AA2/aa2.env

test -e database || mkdir database
test -e database/backup || mkdir database/backup
test -e database/envio || mkdir database/envio
test -e database/sig-upload-data || mkfifo database/sig-upload-data

echo "Installing chancelor..."

(
    mkdir -p "/usr/local/bin/"
    sed 's;\(MYTEMPO_DATA=\);\1'"$(realpath .);" System/chancelor > "/usr/local/bin/chancelor" \
	&& chmod +x "/usr/local/bin/chancelor" \
	&& systemctl link ./System/systemd/system/chancelor.service
) || error "Could not install chancelor, check your perms"

if [ "$UPDATING" = "no" ]; then
    echo "Disabling USB autosuspend (see #3)"

    (
	sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*$/GRUB_CMDLINE_LINUX_DEFAULT="usbcore.autosuspend=-1 loglevel=3 quiet"/' /etc/default/grub \
	    && grub-mkconfig -o /boot/grub/grub.cfg
    ) || error "Could not disable USB autosuspend feature"

    echo "Speeding up boot process"

    (
	systemctl disable systemd-networkd-wait-online.service \
	    && systemctl enable NetworkManager-wait-online.service
    ) || error "Could not switch network configuration method"
fi

[ "$UPDATING" = "yes" ] \
    && ./build \
	|| error "Error while rebuilding the codebase, please file an issue at https://github.com/MyTempoESP/MonoTempo/issues/new?template=BLANK_ISSUE"

read -p "Do you wish to manually setup your configuration files? (N/y): " WISH

[ "$WISH" != "y" ] && healthy_breakup "All done! Please reboot for the changes to take effect."

read -p "Please type the device ID (default: 501): " DEVICE_ID
read -p "Type the device's reader type (impinj/chafon): " READER_TYPE
read -p "Is your Arduino screen programmer detected as ACM or USB? (leave blank if you dont know): " SCREEN_PATH

echo "Setting up hostname"
(echo "my$DEVICE_ID" > /etc/hostname) || error "Could not set machine hostname"

echo "Setting up shared.env"

(
    sed -i "s/MYTEMPO_READER_TYPE=.*$/MYTEMPO_READER_TYPE=$READER_TYPE/" shared.env \
	&& sed -i "s/MYTEMPO_READER=.*$/MYTEMPO_READER=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env \
	&& sed -i "s/MYTEMPO_EQUIP=.*$/MYTEMPO_EQUIP=PORTAL LEITOR RFIDMY${DEVICE_ID:-501}/" shared.env \
	&& sed -i "s/MYTEMPO_DEVID=.*$/MYTEMPO_DEVID=${DEVICE_ID:-501}/" shared.env
) || error "Could not setup shared.env"

echo "Setting up Offline/AA2/aa2.env"

READER_NAME=
[ "$READER_TYPE" = "chafon" ] && READER_NAME=ca
[ "$READER_TYPE" = "impinj" ] && READER_NAME=ff

(
    sed -i "s/READER_NAME=.*$/READER_NAME=$READER_NAME/" Offline/AA2/aa2.env \
	&& sed -i "s;READER_PATH=.*$;READER_PATH=/dev/tty${SCREEN_PATH:-USB}0;" Offline/AA2/aa2.env
) || error "Something went wrong with the setup, i'm not really a sed expert"

echo "Setting reader ip"

[ "$READER_TYPE" = "chafon" ] \
    && sed -i "s/READER_IP=.*$/READER_IP=192.168.1.200/" shared.env || error "Error setting reader IP address"

if [ "$READER_TYPE" = "impinj" ]; then

    read -p "Type the reader IP address: " READER_IP
    sed -i "s/READER_IP=.*$/READER_IP=$READER_IP/" shared.env || error "Error setting reader IP address"
fi

healthy_breakup "All done! Please reboot for the changes to take effect."
