#!/bin/sh

test -e shared.env || cp shared.env.in shared.env
test -e Offline/AA2/aa2.env || cp Offline/AA2/aa2.env.in Offline/AA2/aa2.env

test -e database || mkdir database
test -e database/backup || mkdir database/backup
test -e database/envio || mkdir database/envio
test -e database/sig-upload-data || mkfifo database/sig-upload-data

echo "Installing chancelor..."

# fixed chancelor to local bin
mkdir -p "/usr/local/bin/"

sed 's;\(MYTEMPO_DATA=\);\1'"$(realpath .);" System/chancelor > "/usr/local/bin/chancelor" \
&& chmod +x "/usr/local/bin/chancelor"                                                     \
&& systemctl link ./System/systemd/system/chancelor.service                                \
&& echo "Disabling USB autosuspend (see #3)"                                               \
&& sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/&usbcore.autosuspend=-1 /' /etc/default/grub     \
&& grub-mkconfig -o /boot/grub/grub.cfg                                                    \
&& echo "All done! Please reboot your device for the changes to take place."
