#!/bin/sh

#cp NetworkManager-config/system-connections/* /etc/NetworkManager/system-connections

git pull
git submodule update --init --recursive

mkfifo ./wifi-connection
chmod 0666 ./wifi-connection

docker compose up --build

