#!/bin/sh

set -o xtrace

MYTEMPO_DATA=

reset_wifi() {

    nmcli conn down MyTempo
    sleep 2
    nmcli -w 6 conn up MyTempo
}

while true
do
    read -r COMMAND < "$MYTEMPO_DATA"/database/sig-device-operation

    [ "$COMMAND" = "wifi" ] && reset_wifi
done
