#!/bin/sh

# guard
if grep -q "FIX_FILE_PERM" mytempo.sql; then
	echo "patch already applied"

	exit
fi

(cat >> mytempo.sql) <<end
/*FIX_FILE_PERM*/
GRANT FILE on *.* to mytempo_user@'%';

/*EQUIP_DATA*/
INSERT INTO `equipamento`(`id`, `checkpoint_id`, `idequip`, `modelo`, `event_id`, `tags_unicas`) VALUES (1,0,0,'',0,0); 
end

